### ISSUE TITLE
feature request: ParseAddressCodeResponse should return error info when bad address

### ISSUE THREAD

**Issue by Ljzn** [mobilecoinfoundation/mobilecoin#1117]
Hi, we're using the `ParseAddressCode` method to validate the address in our services. It works well when address is valid. But it does not return any message when the address code is invalid.

If the `ParseAddressCodeResponse` could contains an error message field it would be nice.

**Comment by samdealy** [comment]
After investigating this, we found that the `parse_address_code` [method](https://github.com/mobilecoinfoundation/mobilecoin/blob/master/mobilecoind-json/src/bin/main.rs#L354) returns an error message in `String` form that describes the specific address validation error. This error is mapped from this [method](https://github.com/mobilecoinfoundation/mobilecoin/blob/c296f5c152c888f1ddb1d3f12dedbac70298c188/api/src/display.rs#L56). 

So the error message should be returned, though not in the `ParseAddressCodeResponse` JSON format. We can't put the error message in this JSON response because other users / clients might be expecting the error message to be in `String` format. As such, we'd ask that you consume the error message as a `String`. Feel free to test this out, and let us know if the error `String` does not contain the error message / there's something wrong there.

**Comment by Ljzn** [comment]
@samdealy Thanks for reply. The `string` error in json-api sounds great, unfortunately, we're using the gRPC api of mobilecoind. That doesn't return any error message, depends on the [definition]( https://github.com/mobilecoinfoundation/mobilecoin/blob/a59be4c402b2b71aeb90ac4c4bef29d833501537/mobilecoind/api/proto/mobilecoind_api.proto#L37)
