### ISSUE TITLE
Universal Protobuf Repository

### ISSUE THREAD

**Issue by jcape** [mobilecoinfoundation/mobilecoin#1704]
We should create a new repository which is released on it's own cadence, and contains all the protobufs we care about.

While we're doing this we should create a better directory structure to more easily allow us to bifurcate what exists in `mc_api` into more specific crates (i.e. we should be able to create an `mc_crypto_keys_api` crate that contains the `RistrettoPublic` message).

For now this issue is mainly intended to be a place for discussion, which we may want to put into an MCIP.

**Comment by garbageslam** [comment]
So I guess the prevailing idea so far has been:

* Servers own their own APIs
* Severs are responsible for tests that they are implementing their APIs correctly
* mobilecoin.git should be the source of truth for mobilecoin server APIs and fog APIs
* downstream clients can then always know, if the network is mobilecoin revision X, then they need to use such and such protobufs, by checking out that commit.

You could say, the new repository becomes a submodule in mobilecoin.git, so that everyone can clearly map from a mobilecoin revision to protobufs, but then that creates a lot of complexity as well.

What problem are we hoping to solve by having a separate repo of protobufs?

**Comment by garbageslam** [comment]
Cross posting:

moby team has been using this as a universal protobuf repository successfully: https://buf.build/
