### ISSUE TITLE
Go through FVR and port anything needed for FLR

### ISSUE THREAD

**Issue by jcape** [mobilecoinfoundation/mobilecoin#3181]
- [x] #3226

**Comment by NotGyro** [comment]
So far, it looks like the only changes to port over that were necessary were the metrics changes. FVR had also implemented the ResponderID fix which was needed for FLR, but that was pulled in before this issue was created. So, this was completed in https://github.com/mobilecoinfoundation/mobilecoin/pull/3264 and https://github.com/mobilecoinfoundation/mobilecoin/pull/3267
