### ISSUE TITLE
The field type of response of the mobilecoind-json should be same with the mobilecoind

### ISSUE THREAD

**Issue by jadeydi** [mobilecoinfoundation/mobilecoin#683]
e.g.: 
Amount masked_value https://github.com/mobilecoinfoundation/mobilecoin/blob/master/mobilecoind-json/src/data_types.rs#L488

tombstone_block, fee of JsonTxPrefix, from & to of JsonRange, block_count & txo_count should be Integer, etc.

**Comment by eranrund** [comment]
Hello @jadeydi 

The reason we are using strings instead of integers over JSON is because Javascript (where often JSON is used) does not support 64 bit integers. Please see https://stackoverflow.com/questions/24037751/how-to-do-64bit-integer-arithmetic-in-node-js/24037917 and https://stackoverflow.com/questions/209869/what-is-the-accepted-way-to-send-64-bit-values-over-json

In order to work around that we opted to use strings which can then be converted in the language you are using back to a u64 type without risking losing data.

**Comment by jadeydi** [comment]
Thanks @eranrund, your posts are several years ago, javascript has support builtin object BigInt right now.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt/asUintN
