### ISSUE TITLE
Effect of SGX deprecation?

### ISSUE THREAD

**Issue by quidnu** [mobilecoinfoundation/mobilecoin#813]
What impact does the fact that the newest Intel chips (Tiger and Rocket Lake) no longer include SGX have on MobileCoin?

**Comment by 4oo4** [comment]
I think that's only the consumer side, there are still enterprise-grade chips released this year with SGX:

https://ark.intel.com/content/www/us/en/ark/search/featurefilter.html?productType=873&2_SoftwareGuardExtensions=Yes%20with%20Intel%C2%AE%20

Because of the project's elitist stance towards who can run a node (i.e. someone who can afford one of these expensive CPUs), they probably don't see it as an issue.

Speaking of SGX, I'm curious why  it'sso tightly coupled with the project, given of all the attacks there are against it.

I'm not sure how feasible they are in practice, but to me it seems questionable to rely on SGX so heavily, given how bad Intel's track record is in dealing with silicon or microarchitecutre-based exploits.

* https://www.usenix.org/conference/usenixsecurity18/presentation/bulck
* https://sgaxe.com/
* https://platypusattack.com/
* https://plundervolt.com/
* http://www.cs.cmu.edu/~dskarlat/publications/microScope_isca19.pdf

**Comment by jcape** [comment]
Hi,

@quidnu The removal of SGX from desktop processors isn't great, but it probably won't effect us. As it stands now, the current implementation of on-die GPUs by Intel require they be disabled for SGX to work effectively, which does significantly reduce it's value on a desktop system.

@4004 I'd recommend taking at look at [Why we use SGX for MobileCoin](https://youtu.be/Hwf_Q31woLo?t=284), which goes into greater detail of the (pretty limited) list of things we're using SGX to accomplish.
